---

- name: Intall yum packages.
  yum: pkg={{ item }} state=present
  with_items:
    - denyhosts

- lineinfile:
    dest: /etc/denyhosts.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - regexp: '^ADMIN_EMAIL =.*'
      line: "ADMIN_EMAIL = {{ denyhosts_admin_email }}"
    - regexp: '^BLOCK_SERVICE *=.*'
      line: "BLOCK_SERVICE = {{ denyhosts_block_service }}"

- service: name=denyhosts enabled=yes state=restarted
